#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '
🏗️👷 Checking commit, styling, testing and building your project before committing
'

# Check ESLint
npm run lint ||
(
  echo '😡😒👺 OMG! make that s**t really work! 😡😒👺
    ES Lint Check Failed. Make the required changes listed above, add changes and try to commit again.'
	false;
)

# If everything passes... Now we can commit
# echo '
# 🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔
# '

# npm run build ||
# (
#   echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#     Next build failed: View the errors above to see why.
#   '
#   false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am trying to committ this now. 🤯 ✅✅✅✅
'
